### ISSUE TITLE
Rollback to backup

### ISSUE THREAD

**Issue by Yakrel** [natankeddem/bale#2]
I cant rollback to any zfs backup, what release and hold buttons does exactly ? is there not any rollback option ?

**Comment by natankeddem** [comment]
Implementing a 'zfs rollback' feels a bit too dangerous in this application.  I can think about it but i get conservative around such destructive commands. For now you can as always manually issue 'zfs rollback' on the system directly. 

Hold and release are documented here:
https://openzfs.github.io/openzfs-docs/man/master/8/zfs-hold.8.html
https://openzfs.github.io/openzfs-docs/man/master/8/zfs-release.8.html

**Comment by Yakrel** [comment]
Thank you I hope you add that feature in the future.
